fix: Commit Message file changes

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,15 +1,42 @@
 #!/bin/sh
 
-echo "~~~~**** Commit hook started ****~~~~"
+echo "*****~~~~~ Commit hook initiated ~~~~~~*****"
 
 commit_msg_file=$1
 commit_msg=$(cat "$commit_msg_file")
 
-
 # For formatting your code
-npx prettier --write .
+echo
+echo "*****~~~~~ Formatting - Check for unformatted files ~~~~~~*****"
+
+# Check for unformatted JavaScript, TypeScript, and JSON files using Prettier
+unformatted_js_files=$(git ls-files | grep '\.js\|\.jsx\|\.ts\|\.tsx\|\.json' | xargs npx prettier --list-different)
+
+# If there are unformatted JavaScript, TypeScript, or JSON files, print an error message and exit with a non-zero status code
+if [ -n "$unformatted_js_files" ]; then
+  echo "Error: Unformatted JavaScript, YML or JSON files found. Please run 'npx prettier --write .' for formatting whole repository or 'npx prettier --write' on the following files:"
+  echo "$unformatted_js_files"
+  exit 1
+fi
+
+# Check for unformatted ReScript files
 npm run re:format
 
+echo
+echo "*****~~~~~ All files are formatted. ~~~~~~*****"
+echo
+
+# JS Code Check
+echo "*****~~~~~ Checking ReScript Code ~~~~~~*****"
+if (! npm run re:build)
+then
+    echo "*****~~~~~ ReScript Code Compilation Failed! ~~~~~*****"
+    exit 1
+fi
+
+echo
+echo "*****~~~~~ Commit message validation! ~~~~~*****"
+echo
 # Define your commit message convention (e.g., starts with "feat:", "fix:", etc.)
 commit_regex="^(Merge branch|(feat|fix|chore|refactor|docs|test|style|enhancement):).+"
 
@@ -28,5 +55,5 @@ else
 fi
 
 # If the commit message matches the convention, the script exits successfully.
-echo "~~~~**** Commit hook completed ****~~~~"
+echo "*****~~~~~ Commit hook completed ~~~~~~*****"
 exit 0
